source 'https://cdn.cocoapods.org'
target 'iosApp' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'shared', :path => '../shared'
  
  target 'iosAppTests' do
    inherit! :search_paths
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
